[project]
name = "TeleShelf"
version = "0.1.0"
description = "A bookshelf, but for Telegram media"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.14",
    "sqladmin>=0.21.0",
    "sqlmodel>=0.0.24",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
]
