[project]
name = "TeleShelf"
version = "0.1.0"
description = "A bookshelf, but for Telegram media"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
]
